### ISSUE TITLE
Feature: Leaderboard

### ISSUE THREAD

**Issue by asianviking** [tonymfer/base-world#4]
- Add a leaderboard page to show all countries and stats
- Use shadcn's [Data Table](https://ui.shadcn.com/docs/components/data-table)
- Add sorting options
  - Sort by followers
  - Sort by posts

**Comment by derRizzMeister** [comment]
Closing this as this was treated here: https://github.com/tonypark99/base-globe/commit/990d1e6acdd34a3a4f1558debd4d71dc958cb142
